spring:
  application:
    name: finances-ms-auth

  data:
    mongodb:
      uri: mongodb+srv://${MONGO_USERNAME}:${MONGO_PASSWORD}@finances.ol6kb.mongodb.net/?retryWrites=true&w=majority&appName=finances
      database: financesdbdev

  jpa:
    open-in-view: true

jwt:
  secret: ${SECRET_KEY}

server:
  port: 8200



